version: '3'

services: 
    database:
        image: mariadb
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: users
        ports:
            - 3306:3306
        volumes:
            - ./database:/docker-entrypoint-initdb.d:ro
    
    web_services_template:
        build:
            context: ./web_services_template
            dockerfile: Dockerfile
        environment: 
            FLASK_ENV: development
            FLASK_APP: app.py
        ports:
            - 5000:5000
            
    web_app_template:
        build:
            context: ./web_app_template
            # dockerfile: Dockerfile
        volumes:
            - ./web_app_template/nginx/nginx.conf:/etc/nginx/conf:ro
            - ./web_app_template/nginx/data/certs:/etc/nginx/certs
            # data
        ports:
            - 80:80
            - 443:443
